export const ADDRESS = "Address";
export const ADDRESSMGT="AddressMgt";

export const DEALORDERIDLIST="DEALORDERIDLIST";
export const DEALORDERLIST = "DEALORDER";
export const DEALORDERDETAILS="DEALORDERDETAILS";


export const COUPONORDERIDLIST="COUPONORDERIDLIST";
export const COUPONORDERLIST = "COUPONORDER";
export const COUPONORDERDETAILS="COUPONORDERDETAILS";