export const GETCOUPONSUCCESS="GETCOUPONSUCCESS";
export const GETSEARCHSKUSUCCESS="GETSEARCHSKUSUCCESS";
export const ADDTOBASKET="ADDTOBASKET";
export const UPDATEBASKET="UPDATEBASKET";
export const REMOVESKUBASKET="REMOVESKUBASKET";
export const BASKETDETAIL="BASKETDETAIL";


export const UPDATECOUPONADDRESS="UPDATECOUPONADDRESS";
export const DELETECOUPONADDRESS="DELETECOUPONADDRESS";
export const ADDCOUPONADDRESS="ADDCOUPONADDRESS";


export const UPDATECOUPONRULES="UPDATECOUPONRULES";
export const ADDCOUPON="ADDCOUPON";


export const GETCOUPONDETAILS="GETCOUPONDETAILS";
export const COUPONDETAIL="COUPONDETAIL";
