export const GETDEALS = 'GETDEALS';

export const GETORDERDETAILS='GETORDERDETAILS';
export const GETORDERSUCCESS='GETORDERSUCCESS';



export const SEARCHSKUDEALMGT='SEARCHSKUDEALMGT';
export const GETDEALSLIST='GETDEALSLIST';


export const UPDATEDEAL='UPDATEDEAL';
export const UPDATEDEALSUCCESS="UPDATEDEALSUCCESS";
export const UPDATEDEALFAILED="UPDATEDEALFAILED";
export const UPDATEDEALWARNING=" UPDATEDEALWARNING";




export const ADDDEAL = 'ADDDEAL';

export const REMOVEDEAL = 'REMOVEDEAL';
export const REMOVEDEALSUCCESS='REMOVEDEALSUCCESS';
export const REMOVEDEALFAILED='REMOVEDEALFAILED';


export const GETORDERLIST='GETORDERLIST';
export const CANCELORDERSUCCESS='CANCELORDER';
export const ADDDEALSUCCESS='ADDDEALSUCCESS';
export const ADDDEALFAILED='ADDDEALFAILED';
export const ADDDEALWARNING='ADDDEALWARNING';


export const UPDATEDEALADDRESS="UPDATEDEALADDRESS";
export const DELETEDEALADDRESS="DELETEDEALADDRESS";
export const ADDDEALADDRESS="ADDDEALADDRESS";