export const GETPRODUCTMGT = "GETPRODUCTMGT";
export const SETPRODUCT="SETPRODUCT";
export const GETSKULIST="GETSKULIST";
export const SETSKU="SETSKU";
export const GETSKUDETAILS="GETSKUDETAILS";
export const UPDATESUCCESS="UPDATESUCCESS";
export const ADDSUCCESS="ADDSUCCESS";
export const SETCATEGORY="SETCATEGORY";
export const GETPRODUCTLIST="GETPRODUCTLIST";

export const SEARCHSKUPRODUCTMGT="SEARCHSKU";